### ISSUE TITLE
Can it use for ASR results?

### ISSUE THREAD

**Issue by ILG2021** [pncnmnp/grammatical#1]
I am developing a asr software this days. The asr output has many mistakes related to phonetically similar words (does/thus, week/weak etc.). So can I use chatgpt to fix this type of error?

**Comment by pncnmnp** [comment]
Hey there, I am not 100% certain about this. However, I would encourage you to experiment a bit on ChatGPT's website, try and fine-tune your query and then use it to make API calls.

**Comment by ILG2021** [comment]
ok thanks. I have tried, and it seems not work. I decide to train a t5 model at last.

**Comment by pncnmnp** [comment]
Hey @ILG2021, I'm sure you might have tried something similar, but this prompt kind of worked for me:
```
I am developing a asr software and here's the prompt I get from it:
"He thus his homework every weak."

Can you fix the paragraph, specifically any phonetically similar words that you find. Remember, I want it as close as possible to the above paragraph, so just get rid of the inaccuracies.

In your response, just output a simple JSON file of the format:
{"edited": <STRING>}
Nothing else!
```

**Comment by ILG2021** [comment]
> Hey @ILG2021, I'm sure you might have tried something similar, but this prompt kind of worked for me:
> 
> ```
> I am developing a asr software and here's the prompt I get from it:
> "He thus his homework every weak."
> 
> Can you fix the paragraph, specifically any phonetically similar words that you find. Remember, I want it as close as possible to the above paragraph, so just get rid of the inaccuracies.
> 
> In your response, just output a simple JSON file of the format:
> {"edited": <STRING>}
> Nothing else!
> ```

seems work, thanks very much.
